#! /bin/sh

set -xv
exec 2>>/tmp/bspwm.log

xsetroot -cursor_name left_ptr &
xrandr --output DisplayPort-0 --off --output HDMI-A-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DVI-D-0 --mode 1366x768 --pos 1920x243 --rotate normal&
pkill feh &
pkill polybar &
feh --bg-scale --no-fehbg ~/shared/wall/dark-shadow-in-bloomy-night-2560×1440.jpg ~/wall/dark-shadow-in-bloomy-night-2560×1440.jpg &
killall -q polybar
while pgrp -u $UID -x polybar >/dev/null; do sleep 1; done
#polybar -q main -c ~/.config/polybar/config.ini &
polybar bar-main 2>&1 | tee -a /tmp/bar-main.log & disown
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d HDMI-A-0 I II III IV V
bspc monitor -d DVI-D-0 VI VII VIII IX X

bspc config border_width         1 
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color '#0c0d0e'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
